### ISSUE TITLE
Add styling to the project

### ISSUE THREAD

**Issue by Skylars08** [Skylars08/ROSPL_CAFE_WEBSITE#1]
I want people from the open-source community to collaborate with me in this project.

Please add CSS styling to the project.

**Comment by HARSHITDUBEY44** [comment]
Hi Suhas, I am ready to contribute to your project. I can add CSS styling to your project.

**Comment by RahulAsit** [comment]
Hi Suhas, I am ready to contribute to your project. I can provide JS animations to the project.
